---

- hosts: 10.0.0.30
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

- hosts: 10.0.0.30
  become: true
  roles: 
    - epel

- hosts: 10.0.0.30
  become: true
  roles: 
    - virtualbox_software

# - hosts: 10.0.0.30
#   become: true
#   roles:
#     - update_os


...